version: '3.2'
services:
  blackbox:
    image: prom/blackbox-exporter:v0.24.0
    ports:
    #- 9115:9115
    - 10902:10902
    command:
    - --config.file=/etc/blackbox/blackbox.yml
    volumes:
    - ./config/blackbox.yml:/etc/blackbox/blackbox.yml
