version: '3.2'
services:
  compactor:
    image: thanosio/thanos:main-2023-07-20-cdba35b
    container_name: thanos-compactor
    command:
      - "compact"
      - "--data-dir=/tmp/thanos-compact"
      - "--log.level=debug"
      - "--http-address=0.0.0.0:10902"
      - "--http-grace-period=2m"
      - "--consistency-delay=30m"
      - "--retention.resolution-raw=30d"
      - "--retention.resolution-5m=120d"
      - "--retention.resolution-1h=1y"
      - "--compact.concurrency=1"
      - "--delete-delay=15m"
      - "--wait"
      - "--wait-interval=3m"
      - "--objstore.config-file=./s3/bucket.yaml"
    expose:
      - 10902
    ports:
      - "10902:10902"
    volumes:
      - ./data-compact:/tmp
    networks:
      - thanos

networks:
  thanos: {}
