version: '3.2'
services:
  thanos_store:
    image: thanosio/thanos:main-2023-07-20-cdba35b
    container_name: thanos-store
    volumes:
      - ./store-data:/data
    command:
      - "store"
      - "--log.level=debug"
      - "--objstore.config-file=./s3/bucket.yaml"
      - "--data-dir=/data"
      - "--log.format=logfmt"
      - "--index-cache-size=250MB"
      - "--chunk-pool-size=1GB"
      - "--grpc-address=0.0.0.0:10901"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10902"
      - "--store.grpc.series-max-concurrency=20"
      - "--sync-block-duration=3m"
      - "--block-sync-concurrency=20"
    restart: unless-stopped
    expose:
      - 10901
      - 10902
    ports:
      - '10901:10901'
      - '10902:10902'
    networks:
      - thanos

networks:
  thanos: {}
