type: S3
config: 
  bucket: BUCKETNAME 
  access_key: ACCESSKEY
  secret_key: SECRETKEY
  #endpoint: s3-website-ap-southeast-1.amazonaws.com
  endpoint: s3.ap-southeast-1.amazonaws.com
  region: ap-southeast-1 
  insecure: false
  trace:
    enable: true
