global:
  scrape_interval:     1s
  evaluation_interval: 1s
  external_labels:
    prometheus: prometheus

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'thanos-sidecar'
    static_configs:
      - targets: ['sidecar:10902']

  - job_name: 'thanos-store'
    static_configs:
      - targets: ['172.10.4.238:10904']

  - job_name: 'thanos-query'
    static_configs:
      - targets: ['172.10.4.87:10904']

  - job_name: 'thanos-compact'
    static_configs:
      - targets: ['172.10.4.95:10904']
